### ISSUE TITLE
Could I reuse your schematics?

### ISSUE THREAD

**Issue by goran-mahovlic** [Envious-Data/EnvOpenPico#1]
Hi, I have some audio project that needs RP2040 as MCU so I am wondering can I just reuse your schematics and start from it?

For my board I would redo complete PCB - but if you want I can also check/order and assemble your PCB, and confirm if everything is working...

**Comment by Envious-Data** [comment]
Yep thats fine by me

Im not sure the design works yet since the first set I ordered did not work (actually due to me picking a 5V regulator instead of a 3.3V one, oops), I have just ordered some more with the current itteration that is on github and I'll let you know in about a week or two when they arrive from JLCPCB. 

This PDF may come in useful to you if you havent already come across it.
https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf

**Comment by goran-mahovlic** [comment]
Great, thank you! 
I will recheck everything, and I will change regulator as I already have other one at stock.I will get back to you once I make something out of it...
And I will probably switch to 4 layers pcb...

**Comment by goran-mahovlic** [comment]
I would recommend you to avoid adding via this way - as in bigger production you could end up with lots of tombstones.
I am doing it only if I do not have any other choice, and you could use it if you use via in pad but that is bit expensive.

![bad_practice](https://user-images.githubusercontent.com/4248736/137910756-cccefef1-e2ef-463c-bbb3-a857fac6c54a.png)

**Comment by Envious-Data** [comment]
Just got my JLCPCB order and it appears all 5 MCU boards work fine, will do some more testing on them.

edit: it appears the flash chip I picked isnt compatible with the RP2040, will see about getting a friend to swap them for some Winbond ones.

**Comment by goran-mahovlic** [comment]
Thank you  for info. Next week we will probably need to order test boards.
Is the Winbond footprint the same?

**Comment by Envious-Data** [comment]
Ye the footprint on the board and poinout will fit
- W25Q16FWUXIE
- W25Q16JVUXIM


atleast based on https://www.winbond.com/resource-files/w25q16fw%20revj%2005182017%20sfdp.pdf and https://www.winbond.com/resource-files/w25q16jv%spi%revf%05092017.pdf

Ive seen some other RP2040 boards use flash chips listed in this repo
https://github.com/adafruit/nvm.toml/tree/e5b149599d14a8841167fe552846ca36925b87a0/flash/winbond

Also JLCPCB does stock W25Q16FWUXIE

**Comment by goran-mahovlic** [comment]
Great, I have ordered some W25Q so I will check will it work.

Here is V1.0 - so hopefully most things will work. In next version I will need to move RP2040 and all components as top and bottom parts are separated with printed part that will now have strange hole in the place of MCU. 

https://github.com/intergalaktik/SynthoGame

I will close this issue.

**Comment by goran-mahovlic** [comment]
It works! At least bottom board - LEDs and sound(DAC and AMP) works! 
Now I need to solder top board and connect everything...

![SynthoGame_RGB](https://user-images.githubusercontent.com/4248736/141525127-3680c47f-8250-4848-b24e-b3a6e3400a3b.png)

Still lots of things is missing - including foil (now I have just paper), button caps, encoder, touch screen on top.

![SynthoGame_printed_1](https://user-images.githubusercontent.com/4248736/141764919-731f8539-1401-4a43-8c43-fd8862af0e2d.png)
