### ISSUE TITLE
W25Q16FWUXIE requires 1.65v to 1.95v supply

### ISSUE THREAD

**Issue by xyzz** [Envious-Data/EnvOpenPico#2]
As per the datasheet:
![image](https://user-images.githubusercontent.com/1065521/147392433-8b52ac8f-a2d8-4375-85c9-b073b1ea1c20.png)

It is currently connected to 3.3v I don't think that would work
![image](https://user-images.githubusercontent.com/1065521/147392438-70c65bb6-ba35-41bc-ba6c-b60fad6a3f48.png)

**Comment by Envious-Data** [comment]
Ah I should probably change that to W25Q16JVUXIQ since its a placeholder but not listed as such.

edit: changed the ref to one that would work.
